apiVersion: v1
data: # this is here only for academical purposes. In theory this should not be on github :)
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIloybHZiR2wwYnpwblVpWm5iemt4SVE9PSIKCQl9Cgl9Cn0=
kind: Secret
metadata:
  creationTimestamp: "2022-07-19T16:00:56Z"
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:.dockerconfigjson: {}
        f:type: {}
      manager: kubectl-create
      operation: Update
      time: "2022-07-19T16:00:56Z"
  name: regcred
  namespace: default
  resourceVersion: "42730"
  uid: 96dc90d5-f25e-41d4-92e9-75832b8ed229
type: kubernetes.io/dockerconfigjson
