apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgAy6d1ARL1INGbsDr5IXfE2Fcgw5PQRveV5j91gL5b2Vk+VqUYA3ynCcrw1FS9GUQeTePg3ESir/6hB7H9sMbbHrlnJKenxPpuzzNCZFQVH18pVHRd4JXSBQkPcRXHlkevrblEXjkH64wn8yiMj9Qgwu5kYuQrybcQgDz8r08NMbLlKr6QLWnERYjJZwh366S5JI4814uj4v5Nloxs0r8coCeuaVvHRNfDTtcS61uaoW/Zai56f9hFlRu8o5gvc29p3jlFZMKwy11wivKdMIJtu+KDcG8vxve1ldn9mLvr0j5lOqnMLeh2FC7HL8pXDLG2jZ1XI73YO7oiwOOXnHb/mnh2vNZ0gDdJ8UiZSYePClMmMqr8dGSBR1DGRn3xvts61Ne1Jw1IiIY/38SK5S9bGftqSlYLeKw/ZGbP1Ln2pPjDBHFPGaEladSt/CvJmMy0zXQe9FfpOcmVy1DY8kf/9PercOrNhmteThHfqTzb3oXv1ehwiu7c1M1XsSzFJnc9GPpuEEWAcSN3aqUIf6b1aFjtjrgmocg7dUGVjjpgSnQ5xDQdbLvBLg6zEZKTWSH4gcxhQWVb2itbHtRN0QdSrXaMajtQGERiRo9x4vIjooPtAHIKfy5YdQjXHn43ldUK19XGPb62G+waOSsncfNmy53UZHhGPc67VjQSiXhov3bklDQO2rVFlr8oOsin6Ze5C/VSxRTSulGlr8/kuWsiqxdBtM4lr/a0BBKip6RWLyhAwwDDkfj5G9L7qdy1stOvh/pMqnW3Vv70npPF/9LpMHS12EDCCvasub0DZd6wkYXjZUI+s44+CFa2qXHDUog==
  template:
    metadata:
      creationTimestamp: null
      managedFields:
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            .: {}
            f:.dockerconfigjson: {}
          f:type: {}
        manager: kubectl-create
        operation: Update
        time: "2022-07-19T16:00:56Z"
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson

