apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fe-secrets
  namespace: default
spec:
  encryptedData:
    telegram_token: AgAIJX22G+oizW5/3mV9QFPyXuR9Lr5bhEjQwfQNoqADb96daF/nXS38VM02KaO+g8is+oygEOlaFjYGqgKjicU1kz8gdbr8xA5ceFZsHjnKimPPxvyy6Ouinr61+kW2OyMEoEF9lsxudBF2z6xX/LW/G1kxstthYR0UYvilbzL9Wu7qgaw0j993Esv+sadn7CR5RFh9Rvyry5hcQ7zsbPTcJZivbuBJbTDxqeRU7tdvZ1HfdioQS8Hr2zFLy+t7svNii5BTwJBY77tOwSmMsBN4RJ/YwEHNDEsm0EYm+l1penKidQfb9ql4yEMJYBYQJOvzAosorLsPp6ump0pgKbL762McISjwUyTejYpUF1Ycc9gv3CU1w5mEzAlRT421CrgYn13ghHAaRFy5ivu7NwC6V2o0DnvRvpBHf0lLGPkVHZAbkjRYLvJL+MlNsrN/RzXqdcn9P/dBDBe7IJ4XMsHxm/46KUkwAd3Ut7e01hSiITE9KUelptr7n1fHjFxdI3LbEQL/vu6UsSsyXNU5G8QLHfIDLfyi/f3WlbB0/O3nfQs/xvNBWwfxEOcnBJ3m9bU1S5QU9cbOb7FxGSB0w6us3l+VEj9kFOAg9h/4myzZQ2by6J0Bqc+V9HTyemiEdy9vnK/VSaQmWUd2qWWeJ6ZMEFvxfMKy07w9i5rz2qyGXuyXb1u+dTTKZFzNIWxTzpwEg4PkJ7SvLSqCgHL7eTIJeFcbiH83yZJf6ea/RgImqrPlHyQwlYBKMDecblah
  template:
    metadata:
      creationTimestamp: null
      name: fe-secrets
      namespace: default

